/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package com.itson.interfaz;

import com.itson.implementaciones.PersonaDAO;
import interfaces.IPersonaDAO;
import java.awt.Cursor;
import javax.swing.JOptionPane;

/**
 *
 * Pantalla inicial de la aplicacion
 *
 * @author arace
 */
public class Aplicacion extends javax.swing.JFrame {

    private final IPersonaDAO a = new PersonaDAO();

    /**
     * Creates new form Aplicacion Form Aplicacion
     */
    public Aplicacion() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new utils.RoundedPanel();
        btnModuloLicencia = new utils.RoundedPanel();
        lblImgLicencia = new javax.swing.JLabel();
        labelOperacion1 = new javax.swing.JLabel();
        btnModuloPlaca = new utils.RoundedPanel();
        lblImgPlaca = new javax.swing.JLabel();
        labelOperacion3 = new javax.swing.JLabel();
        btnModuloConsulta = new utils.RoundedPanel();
        lblImgConsulta = new javax.swing.JLabel();
        labelOperacion4 = new javax.swing.JLabel();
        btnModuloReporte = new utils.RoundedPanel();
        lblImgReporte = new javax.swing.JLabel();
        labelOperacion5 = new javax.swing.JLabel();
        labelOperacion = new javax.swing.JLabel();
        botonPersonas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia fiscal");
        setBackground(new java.awt.Color(153, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogo.setBackground(new java.awt.Color(7, 92, 79));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoAgencia.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addContainerGap(400, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(336, 336, 336))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLogoLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        jPanel1.setBackground(new java.awt.Color(15, 153, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setRoundBottomLeft(50);
        roundedPanel1.setRoundBottomRight(50);
        roundedPanel1.setRoundTopLeft(50);
        roundedPanel1.setRoundTopRight(50);

        btnModuloLicencia.setBackground(new java.awt.Color(204, 204, 204));
        btnModuloLicencia.setRoundBottomLeft(50);
        btnModuloLicencia.setRoundBottomRight(50);
        btnModuloLicencia.setRoundTopLeft(50);
        btnModuloLicencia.setRoundTopRight(50);
        btnModuloLicencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModuloLicenciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModuloLicenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModuloLicenciaMouseExited(evt);
            }
        });

        lblImgLicencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/licencia-de-conducir.png"))); // NOI18N

        labelOperacion1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion1.setForeground(new java.awt.Color(0, 0, 0));
        labelOperacion1.setText("Módulo de licencias");

        javax.swing.GroupLayout btnModuloLicenciaLayout = new javax.swing.GroupLayout(btnModuloLicencia);
        btnModuloLicencia.setLayout(btnModuloLicenciaLayout);
        btnModuloLicenciaLayout.setHorizontalGroup(
            btnModuloLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloLicenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOperacion1)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModuloLicenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgLicencia)
                .addGap(55, 55, 55))
        );
        btnModuloLicenciaLayout.setVerticalGroup(
            btnModuloLicenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloLicenciaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblImgLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOperacion1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnModuloPlaca.setBackground(new java.awt.Color(204, 204, 204));
        btnModuloPlaca.setRoundBottomLeft(50);
        btnModuloPlaca.setRoundBottomRight(50);
        btnModuloPlaca.setRoundTopLeft(50);
        btnModuloPlaca.setRoundTopRight(50);
        btnModuloPlaca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModuloPlacaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModuloPlacaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModuloPlacaMouseExited(evt);
            }
        });

        lblImgPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/placa.png"))); // NOI18N

        labelOperacion3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion3.setForeground(new java.awt.Color(0, 0, 0));
        labelOperacion3.setText("Módulo de placas");

        javax.swing.GroupLayout btnModuloPlacaLayout = new javax.swing.GroupLayout(btnModuloPlaca);
        btnModuloPlaca.setLayout(btnModuloPlacaLayout);
        btnModuloPlacaLayout.setHorizontalGroup(
            btnModuloPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloPlacaLayout.createSequentialGroup()
                .addGroup(btnModuloPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnModuloPlacaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblImgPlaca))
                    .addGroup(btnModuloPlacaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelOperacion3)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        btnModuloPlacaLayout.setVerticalGroup(
            btnModuloPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloPlacaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblImgPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOperacion3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnModuloConsulta.setBackground(new java.awt.Color(204, 204, 204));
        btnModuloConsulta.setRoundBottomLeft(50);
        btnModuloConsulta.setRoundBottomRight(50);
        btnModuloConsulta.setRoundTopLeft(50);
        btnModuloConsulta.setRoundTopRight(50);
        btnModuloConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModuloConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModuloConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModuloConsultaMouseExited(evt);
            }
        });

        lblImgConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/consulta.png"))); // NOI18N

        labelOperacion4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion4.setForeground(new java.awt.Color(0, 0, 0));
        labelOperacion4.setText("Módulo de consultas");

        javax.swing.GroupLayout btnModuloConsultaLayout = new javax.swing.GroupLayout(btnModuloConsulta);
        btnModuloConsulta.setLayout(btnModuloConsultaLayout);
        btnModuloConsultaLayout.setHorizontalGroup(
            btnModuloConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOperacion4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModuloConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImgConsulta)
                .addGap(55, 55, 55))
        );
        btnModuloConsultaLayout.setVerticalGroup(
            btnModuloConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloConsultaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblImgConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOperacion4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        btnModuloReporte.setBackground(new java.awt.Color(204, 204, 204));
        btnModuloReporte.setRoundBottomLeft(50);
        btnModuloReporte.setRoundBottomRight(50);
        btnModuloReporte.setRoundTopLeft(50);
        btnModuloReporte.setRoundTopRight(50);
        btnModuloReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModuloReporteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModuloReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModuloReporteMouseExited(evt);
            }
        });

        lblImgReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/portapapeles.png"))); // NOI18N

        labelOperacion5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion5.setForeground(new java.awt.Color(0, 0, 0));
        labelOperacion5.setText("Módulo de reportes");

        javax.swing.GroupLayout btnModuloReporteLayout = new javax.swing.GroupLayout(btnModuloReporte);
        btnModuloReporte.setLayout(btnModuloReporteLayout);
        btnModuloReporteLayout.setHorizontalGroup(
            btnModuloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloReporteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(btnModuloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModuloReporteLayout.createSequentialGroup()
                        .addComponent(lblImgReporte)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnModuloReporteLayout.createSequentialGroup()
                        .addComponent(labelOperacion5)
                        .addContainerGap())))
        );
        btnModuloReporteLayout.setVerticalGroup(
            btnModuloReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnModuloReporteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblImgReporte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOperacion5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModuloLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModuloPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModuloConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModuloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnModuloReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuloConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuloPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModuloLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 1060, 360));

        labelOperacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion.setForeground(new java.awt.Color(255, 255, 255));
        labelOperacion.setText("Selecccione la operación a realizar");
        jPanel1.add(labelOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        botonPersonas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPersonas.setText("Inserción de personas");
        botonPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonasActionPerformed(evt);
            }
        });
        jPanel1.add(botonPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 442, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1200, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton que hace la insersion de las 20 personas ya registradas
     *
     * @param evt la accion a enviar
     */
    private void botonPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonasActionPerformed
        long numeroPersonas = a.contarPersonas();
        if (numeroPersonas >= 20) {
            int respuesta = JOptionPane.showConfirmDialog(null, "Ya hay más de 20 personas registradas en la base de datos. ¿Quiere volver a ingresarlas?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                a.insertarPersonas();
                JOptionPane.showMessageDialog(null, "Se insertaron 20 personas exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            a.insertarPersonas();
            JOptionPane.showMessageDialog(null, "Se insertaron 20 personas exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonPersonasActionPerformed

    /**
     * Boton que envia a la interfaz de modulo de licencia
     *
     * @param evt la accion a enviar
     */
    private void btnModuloLicenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloLicenciaMouseClicked
        ConsultaLicencia v = new ConsultaLicencia();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloLicenciaMouseClicked

    /**
     * Botón que cambia el cursor
     *
     * @param evt la accion a enviar
     */
    private void btnModuloLicenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloLicenciaMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnModuloLicenciaMouseEntered

    /**
     * Botón que cambia el cursor
     *
     * @param evt el evento de mouse
     */
    private void btnModuloLicenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloLicenciaMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnModuloLicenciaMouseExited

    /**
     * Boton que envia a la interfaz modulo de placas
     *
     * @param evt la accion a enviar
     */
    private void btnModuloPlacaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloPlacaMouseClicked
        ConsultaPlaca v = new ConsultaPlaca();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloPlacaMouseClicked

    /**
     * Cambia el cursor al estilo "mano" cuando el mouse se posiciona sobre el
     * botón del módulo de placas.
     *
     * @param evt el evento de mouse
     */
    private void btnModuloPlacaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloPlacaMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnModuloPlacaMouseEntered

    /**
     * Cambia el cursor al cursor por defecto cuando el mouse sale del área del
     * botón del módulo de placas.
     *
     * @param evt evento del mouse
     */
    private void btnModuloPlacaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloPlacaMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnModuloPlacaMouseExited

    /**
     * Boton que envia a la interfaz consulta personas
     *
     * @param evt la accion a enviar
     */
    private void btnModuloConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloConsultaMouseClicked
        ConsultaPersona v = new ConsultaPersona();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloConsultaMouseClicked

    /**
     * Cambia el cursor "mano" cuando el mouse se posiciona sobre le boton
     * modulo de consulta
     *
     * @param evt evento del mouse
     */
    private void btnModuloConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloConsultaMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnModuloConsultaMouseEntered

    /**
     * Cambia el cursor al cursor por defecto cuando el mouse sale del área del
     * botón del módulo de consulta.
     *
     * @param evt evento del mouse
     */
    private void btnModuloConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloConsultaMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnModuloConsultaMouseExited

    /**
     * Boton que envia a la interfaz consultas de persona tramite
     *
     * @param evt la accion a enviar
     */
    private void btnModuloReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloReporteMouseClicked
        ConsultaPersonaTramite v = new ConsultaPersonaTramite();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModuloReporteMouseClicked

    /**
     * Cambia el cursor "mano" cuando el mouse se posiciona sobre le boton
     * modulo de reporte
     *
     * @param evt evento del mouse
     */
    private void btnModuloReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloReporteMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnModuloReporteMouseEntered

    /**
     * Cambia el cursor al cursor por defecto cuando el mouse sale del área del
     * botón del módulo de reporte.
     *
     * @param evt evento del mouse
     */
    private void btnModuloReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModuloReporteMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnModuloReporteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPersonas;
    private utils.RoundedPanel btnModuloConsulta;
    private utils.RoundedPanel btnModuloLicencia;
    private utils.RoundedPanel btnModuloPlaca;
    private utils.RoundedPanel btnModuloReporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelOperacion;
    private javax.swing.JLabel labelOperacion1;
    private javax.swing.JLabel labelOperacion2;
    private javax.swing.JLabel labelOperacion3;
    private javax.swing.JLabel labelOperacion4;
    private javax.swing.JLabel labelOperacion5;
    private javax.swing.JLabel lblImgConsulta;
    private javax.swing.JLabel lblImgLicencia;
    private javax.swing.JLabel lblImgLicencia1;
    private javax.swing.JLabel lblImgPlaca;
    private javax.swing.JLabel lblImgReporte;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel pnlLogo;
    private utils.RoundedPanel roundedPanel1;
    private utils.RoundedPanel roundedPanel3;
    // End of variables declaration//GEN-END:variables

}
