/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.interfaz;

import com.itson.dominio.Persona;
import com.itson.implementaciones.PersonaDAO;
import interfaces.IPersonaDAO;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ildex
 */
public class ConsultaPersona extends javax.swing.JFrame {

    IPersonaDAO a = new PersonaDAO();

    /**
     * Creates new form BusquedaLicencia
     */
    public ConsultaPersona() {
        initComponents();
    }

    public void agregarPersonas(List<Persona> personas) {
        DefaultTableModel modelo = (DefaultTableModel) tblMostrarP.getModel();
        for (Persona persona : personas) {
            Object[] fila = {persona.getRfc(), persona.getNombre(), persona.getApellidoPaterno(), persona.getApellidoMaterno(), persona.getFechaNacimiento(), persona.getTelefono()};
            modelo.addRow(fila);
        }
    }

    public void consultarPersonas(String rfc, String nombre, LocalDate fechaNacimiento) {
        List<Persona> personas = a.buscarPersonas(rfc, nombre, fechaNacimiento);
        agregarPersonas(personas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBuscarParametros = new javax.swing.JLabel();
        labelModuloConsulta = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarP = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtRFC = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();
        dateFechaN = new com.github.lgooddatepicker.components.DatePicker();
        labelRFC = new javax.swing.JLabel();
        labelNombreCompleto = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBuscarParametros.setText("Buscar parametros:");
        labelBuscarParametros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(labelBuscarParametros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 129, -1, -1));

        labelModuloConsulta.setText("Modulo de consulta a personas");
        labelModuloConsulta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(labelModuloConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        tblMostrarP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RFC", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Fecha nacimiento", "Télefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMostrarP.setColumnSelectionAllowed(true);
        tblMostrarP.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblMostrarP);
        tblMostrarP.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblMostrarP.getColumnModel().getColumnCount() > 0) {
            tblMostrarP.getColumnModel().getColumn(0).setResizable(false);
            tblMostrarP.getColumnModel().getColumn(1).setResizable(false);
            tblMostrarP.getColumnModel().getColumn(2).setResizable(false);
            tblMostrarP.getColumnModel().getColumn(3).setResizable(false);
            tblMostrarP.getColumnModel().getColumn(4).setResizable(false);
            tblMostrarP.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 970, 90));

        btnBuscar.setText("Buscar");
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 380, 27));

        txtRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRFCActionPerformed(evt);
            }
        });
        getContentPane().add(txtRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 27));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));
        getContentPane().add(dateFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 280, 30));

        labelRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRFC.setText("RFC");
        getContentPane().add(labelRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        labelNombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombreCompleto.setText("Nombre completo");
        getContentPane().add(labelNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        labelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFecha.setText("Fecha");
        getContentPane().add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 700, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String RFC = txtRFC.getText();
        String NombreCompleto = txtNombre.getText();
        LocalDate fechaN = dateFechaN.getDate();
        consultarPersonas(RFC, NombreCompleto, fechaN);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRFCActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JButton btnBuscar;
    private com.github.lgooddatepicker.components.DatePicker dateFechaN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscarParametros;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelModuloConsulta;
    private javax.swing.JLabel labelNombreCompleto;
    private javax.swing.JLabel labelRFC;
    private javax.swing.JTable tblMostrarP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRFC;
    // End of variables declaration//GEN-END:variables
}
