/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.interfaz;

/**
 *
 * @author ildex
 */
public class ConsultaPersona extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaLicencia
     */
    public ConsultaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBuscarParametros = new javax.swing.JLabel();
        labelModuloConsulta = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarPersonas = new javax.swing.JTable();
        botonBuscar = new javax.swing.JButton();
        campoTextoNombre = new javax.swing.JTextField();
        campoTextoRFC = new javax.swing.JTextField();
        botonSiguiente = new javax.swing.JButton();
        datePícker = new com.github.lgooddatepicker.components.DatePicker();
        labelRFC = new javax.swing.JLabel();
        labelNombreCompleto = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelBuscarParametros.setText("Buscar parametros:");
        labelBuscarParametros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(labelBuscarParametros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 129, -1, -1));

        labelModuloConsulta.setText("Modulo de consulta a personas");
        labelModuloConsulta.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(labelModuloConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        botonRegresar.setText("Regresar");
        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        tablaMostrarPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Seleccionar", "RFC", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Télefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaMostrarPersonas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 740, 50));

        botonBuscar.setText("Buscar");
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, -1, -1));

        campoTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(campoTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 380, 27));

        campoTextoRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoRFCActionPerformed(evt);
            }
        });
        getContentPane().add(campoTextoRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 27));

        botonSiguiente.setText("Siguiente");
        botonSiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));
        getContentPane().add(datePícker, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 180, 30));

        labelRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRFC.setText("RFC");
        getContentPane().add(labelRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        labelNombreCompleto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNombreCompleto.setText("Nombre completo");
        getContentPane().add(labelNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        labelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelFecha.setText("Fecha");
        getContentPane().add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, -1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 700, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void campoTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNombreActionPerformed

    private void campoTextoRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoRFCActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JTextField campoTextoNombre;
    private javax.swing.JTextField campoTextoRFC;
    private com.github.lgooddatepicker.components.DatePicker datePícker;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBuscarParametros;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelModuloConsulta;
    private javax.swing.JLabel labelNombreCompleto;
    private javax.swing.JLabel labelRFC;
    private javax.swing.JTable tablaMostrarPersonas;
    // End of variables declaration//GEN-END:variables
}
