/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.interfaz;

import com.itson.dominio.CostoTramite;
import com.itson.dominio.Persona;
import com.itson.implementaciones.LicenciaDAO;
import com.itson.implementaciones.PersonaDAO;
import com.itson.implementaciones.PlacaDAO;
import java.awt.Cursor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arace
 */
public class CostosPlacas extends javax.swing.JFrame {

    PersonaDAO a = new PersonaDAO();
    CostoTramite b = new CostoTramite();
    LicenciaDAO c = new LicenciaDAO();
    PlacaDAO d = new PlacaDAO();
    private final String rfc;

    /**
     * Creates new form CostosPlacas
     *
     * @param rfc
     */
    public CostosPlacas(String rfc) {
        initComponents();
        setResizable(false);
        this.rfc = rfc;
        this.insertarDatosPersona();
        this.insertarDatosTablaCosto();
        Persona persona = a.buscarPersonasRFC(rfc);
        if (d.validaPersonaPlacas(persona) == true) {
            btnVehiculoUsado.setEnabled(true);
        } else{
            btnVehiculoUsado.setEnabled(false);
        }
    }

    private void insertarDatosPersona() {
        Persona persona = this.a.buscarPersonasRFC(rfc);
        lblPersona.setText("Persona: " + persona.getNombre() + " " + persona.getApellidoPaterno() + " " + persona.getApellidoMaterno());
        if (c.validarLicenciaVigente(persona.getRfc()) == true) {
            lblLicenciaVigencia.setText("Licencia: Vigente");
        } else {
            lblLicenciaVigencia.setText("Licencia: No vigente");
        }
    }

    private void insertarDatosTablaCosto() {
        DefaultTableModel tblCosto = (DefaultTableModel) tblPrecioPlaca.getModel();
        tblPrecioPlaca.setModel(tblCosto);
        tblCosto.addRow(new Object[]{"Placas vehículo nuevo", b.placaNuevo});
        tblCosto.addRow(new Object[]{"Placas vehículo usado", b.placaUsado});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogo = new javax.swing.JPanel();
        labelOperacion = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new utils.RoundedPanel();
        labelTipoCarro = new javax.swing.JLabel();
        btnVehiculoNuevo = new javax.swing.JButton();
        btnVehiculoUsado = new javax.swing.JButton();
        ScrollCostos = new javax.swing.JScrollPane();
        tblPrecioPlaca = new javax.swing.JTable();
        lblPersona = new javax.swing.JLabel();
        lblLicenciaVigencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módulo de placas: Tramitar placa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogo.setBackground(new java.awt.Color(7, 92, 79));

        labelOperacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        labelOperacion.setForeground(new java.awt.Color(255, 255, 255));
        labelOperacion.setText("Módulo de placas: Tramitar placa");

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha-izquierda (1).png"))); // NOI18N
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelOperacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(42, 42, 42))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(labelOperacion))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 90));

        jPanel1.setBackground(new java.awt.Color(15, 153, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setRoundBottomLeft(50);
        roundedPanel1.setRoundBottomRight(50);
        roundedPanel1.setRoundTopLeft(50);
        roundedPanel1.setRoundTopRight(50);
        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTipoCarro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        labelTipoCarro.setForeground(new java.awt.Color(0, 0, 0));
        labelTipoCarro.setText("Seleccione su tipo de vehículo");
        roundedPanel1.add(labelTipoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        btnVehiculoNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVehiculoNuevo.setText("Vehículo nuevo");
        btnVehiculoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoNuevoActionPerformed(evt);
            }
        });
        roundedPanel1.add(btnVehiculoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        btnVehiculoUsado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVehiculoUsado.setText("Vehículo usado");
        btnVehiculoUsado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculoUsadoActionPerformed(evt);
            }
        });
        roundedPanel1.add(btnVehiculoUsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        tblPrecioPlaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPrecioPlaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tramite", "Costo normal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrecioPlaca.getTableHeader().setReorderingAllowed(false);
        ScrollCostos.setViewportView(tblPrecioPlaca);
        if (tblPrecioPlaca.getColumnModel().getColumnCount() > 0) {
            tblPrecioPlaca.getColumnModel().getColumn(0).setResizable(false);
            tblPrecioPlaca.getColumnModel().getColumn(1).setResizable(false);
        }

        roundedPanel1.add(ScrollCostos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 483, 55));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 520, 420));

        lblPersona.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(lblPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 40));

        lblLicenciaVigencia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(lblLicenciaVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 690, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiculoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoNuevoActionPerformed
        RegistroAuto v = new RegistroAuto(rfc);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVehiculoNuevoActionPerformed

    private void btnVehiculoUsadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculoUsadoActionPerformed
        RenovacionPlacas v = new RenovacionPlacas(rfc);
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVehiculoUsadoActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        ConsultaPlaca v = new ConsultaPlaca();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRegresarMouseExited

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CostosPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CostosPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CostosPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CostosPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CostosPlacas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollCostos;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JButton btnVehiculoNuevo;
    private javax.swing.JButton btnVehiculoUsado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelOperacion;
    private javax.swing.JLabel labelTipoCarro;
    private javax.swing.JLabel lblLicenciaVigencia;
    private javax.swing.JLabel lblPersona;
    private javax.swing.JPanel pnlLogo;
    private utils.RoundedPanel roundedPanel1;
    private javax.swing.JTable tblPrecioPlaca;
    // End of variables declaration//GEN-END:variables
}
