/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.interfaz;

import com.itson.dominio.Automovil;
import com.itson.dominio.CostoTramite;
import com.itson.dominio.Persona;
import com.itson.dominio.Placa;
import com.itson.implementaciones.LicenciaDAO;
import com.itson.implementaciones.PersonaDAO;
import com.itson.implementaciones.PlacaDAO;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arace
 */
public class RenovacionPlacas extends javax.swing.JFrame {

    PersonaDAO a = new PersonaDAO();
    CostoTramite b = new CostoTramite();
    LicenciaDAO c = new LicenciaDAO();
    PlacaDAO d = new PlacaDAO();
    private static final Logger LOG = Logger.getLogger(PlacaDAO.class.getName());
    private final String rfc;

    /**
     * Creates new form RenovacionPlacas
     *
     * @param rfc
     */
    public RenovacionPlacas(String rfc) {
        initComponents();
        this.rfc = rfc;
    }

    private void cargarTablaAuto(String placa) {
        Persona persona = a.buscarPersonasRFC(rfc);
        try {
            List<Automovil> listaAuto = d.buscarPlacaAutomovilL(placa, persona);
            DefaultTableModel modeloTabla = (DefaultTableModel) this.tblAuto.getModel();
            modeloTabla.setRowCount(0);
            for (Automovil auto : listaAuto) {
                Object[] fila = {
                    auto.getSerie(),
                    auto.getMarca(),
                    auto.getLinea(),
                    auto.getColor(),
                    auto.getModelo()
                };
                modeloTabla.addRow(fila);
            }
        } catch (Exception e) {
            LOG.log(Level.SEVERE, e.getMessage());
        }
    }

    private void validaPlaca() {
        Persona persona = a.buscarPersonasRFC(rfc);
        if (txtPlaca.getText().equals("   -   ")) {
            JOptionPane.showMessageDialog(null, "El campo de texto de placa está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        this.cargarTablaAuto(txtPlaca.getText());
//        } else if (d.validaPlacaPersonaExiste(txtPlaca.getText(), persona) == false) {
//            JOptionPane.showMessageDialog(null, "La placa " + txtPlaca.getText() + " no tiene coincidencia con una placa registrada en nuestro sistema", "ERROR", JOptionPane.ERROR_MESSAGE);
//            System.out.println(d.validaPlacaPersonaExiste(txtPlaca.getText(), persona));
//        } else {
//            this.cargarTablaAuto(txtPlaca.getText());
//            System.out.println(d.validaPlacaPersonaExiste(txtPlaca.getText(), persona));
//        }
    }

    private void insertarPlaca() {
        Persona persona = a.buscarPersonasRFC(rfc);
        Automovil auto = d.buscarPlacaAutomovil(txtPlaca.getText(), persona);
        Double costo = b.placaUsado;
        String placa = d.generarPlaca();
        d.insertarTramitePlacasUsado(persona, auto, placa, costo);
        JOptionPane.showMessageDialog(null, "Se ha renovado la placa para el vehiculo:\n"
                + "Placa: " + placa + "\n"
                + "No. Serie: " + auto.getSerie() + "\n"
                + "Marca: " + auto.getMarca() + "\n"
                + "Linea: " + auto.getLinea() + "\n"
                + "Color: " + auto.getColor() + "\n"
                + "Modelo: " + auto.getModelo() + "", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        Aplicacion v = new Aplicacion();
        v.setVisible(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelIngresarPlacas = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuto = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        txtPlaca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Renovacion de Placas");

        labelIngresarPlacas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelIngresarPlacas.setText("Ingrese placas");

        botonAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonRegresar.setText("Regresar");

        tblAuto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serie", "Marca", "Línea", "Color", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAuto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblAuto);
        if (tblAuto.getColumnModel().getColumnCount() > 0) {
            tblAuto.getColumnModel().getColumn(0).setResizable(false);
            tblAuto.getColumnModel().getColumn(1).setResizable(false);
            tblAuto.getColumnModel().getColumn(2).setResizable(false);
            tblAuto.getColumnModel().getColumn(3).setResizable(false);
            tblAuto.getColumnModel().getColumn(4).setResizable(false);
        }

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        try {
            txtPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAA-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(labelIngresarPlacas)
                                .addGap(28, 28, 28)
                                .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(botonRegresar)
                        .addGap(117, 117, 117)
                        .addComponent(botonAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIngresarPlacas)
                    .addComponent(btnBuscar)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonRegresar))
                .addGap(56, 56, 56))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        this.insertarPlaca();
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.validaPlaca();
    }//GEN-LAST:event_btnBuscarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RenovacionPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RenovacionPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RenovacionPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RenovacionPlacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new RenovacionPlacas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIngresarPlacas;
    private javax.swing.JTable tblAuto;
    private javax.swing.JFormattedTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
